### ISSUE TITLE
lora训练

### ISSUE THREAD

**Issue by lanchongdashygo** [CSHaitao/LexiLaw#26]
你好，我想请问一下，我在服务器上使用项目中的lora训练的时候，发现磁盘空间不足，因为服务器系统盘的大小是固定的，所以可能无法调整系统盘的大小，请问lora下载的模型一般会保存在哪里呢？更改lora下载模型的地址到数据盘会有效解决这个问题吗？该如何使这个过程顺利地继续训练下去呢？万分感谢大佬们的解答！

**Comment by CSHaitao** [comment]
可以修改保存地址，在sh文件中有的

**Comment by lanchongdashygo** [comment]
> 可以修改保存地址，在sh文件中有的

好的非常感谢，已经调整了路径
