### ISSUE TITLE
checkpoint

### ISSUE THREAD

**Issue by lanchongdashygo** [CSHaitao/LexiLaw#27]
请问在lora训练的过程中是不是不会产出checkpoint，这样如果出现错误就需要完全重来，可以麻烦告知如何在训练过程中每隔一定的训练文件就生成checkpoint吗？万分感谢！

**Comment by CSHaitao** [comment]
会的，运行文件有隔多少步一保存的参数

**Comment by lanchongdashygo** [comment]
> 会的，运行文件有隔多少步一保存的参数

好的我再找找看

**Comment by lanchongdashygo** [comment]
> 会的，运行文件有隔多少步一保存的参数

您好，checkpoint确实存在，请问该如何运行这些checkpoint呢，是将adapter.bin和trainer_state.json文件分别替换，然后执行python inference_lora.py即可吗？
